default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: <%= ENV['db.host'] %>
  username: <%= ENV['db.username'] %>
  password: <%= ENV['db.password'] %>

development:
  <<: *default
  database: cdms_development

test:
  <<: *default
  database: cdms_test
